// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProductApi.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ProductApi.Models
{
    public partial class ExamProductContext
    {
        private IExamProductContextProcedures _procedures;

        public virtual IExamProductContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ExamProductContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IExamProductContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<USP_GetProductsResult>().HasNoKey().ToView(null);
        }
    }

    public partial class ExamProductContextProcedures : IExamProductContextProcedures
    {
        private readonly ExamProductContext _context;

        public ExamProductContextProcedures(ExamProductContext context)
        {
            _context = context;
        }

        public virtual async Task<List<USP_GetProductsResult>> USP_GetProductsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<USP_GetProductsResult>("EXEC @returnValue = [dbo].[USP_GetProducts]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
