// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProductApi.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ProductApi.Models
{
    public partial interface IExamProductContextProcedures
    {
        Task<List<USP_GetProductsResult>> USP_GetProductsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
