// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductApi.Models
{
    public partial class Product
    {
        public string Sku { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int CategoryId { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public string Icon { get; set; }
        public string Image { get; set; }

        public virtual Category Category { get; set; }
    }
}